apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: msa-nodepool
spec:
  template:
    metadata:
      labels:
        workload: msa
    spec:
      nodeClassRef:
        group: eks.amazonaws.com
        kind: NodeClass
        name: default

      requirements:
        - key: "eks.amazonaws.com/instance-category"
          operator: In
          values: ["c", "m"]
        - key: "topology.kubernetes.io/zone"
          operator: In
          values: ["ap-northeast-2a", "ap-northeast-2b", "ap-northeast-2c"]
        - key: "kubernetes.io/arch"
          operator: In
          values: ["amd64"]

  limits:
    cpu: "1000"
    memory: 4Gi
